-- MySQL Script generated by MySQL Workbench
-- lun. 20 avril 2020 10:53:35 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mdp` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `create_time` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `points fidelite` INT NULL,
  `tel` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_clients_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`employés`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employés` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employés_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_employés_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`livreurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livreurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_longitude` DECIMAL(50,30) NULL,
  `position_magnitude` DECIMAL(50,30) NULL,
  `statut` TINYINT NULL,
  `employés_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livreurs_employés1_idx` (`employés_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `employés_id_UNIQUE` (`employés_id` ASC) VISIBLE,
  CONSTRAINT `fk_livreurs_employés1`
    FOREIGN KEY (`employés_id`)
    REFERENCES `mydb`.`employés` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`adresses_clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adresses_clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `rue` VARCHAR(45) NULL,
  `code postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `complement` VARCHAR(45) NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adresses_clients1_idx` (`clients_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_adresses_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `code postal` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commandes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresses_clients_id` INT NOT NULL,
  `livreurs_id` INT NOT NULL,
  `date` DATETIME NULL,
  `statut` VARCHAR(45) NULL,
  `restaurants_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commandes_adresses1_idx` (`adresses_clients_id` ASC) VISIBLE,
  INDEX `fk_commandes_livreurs1_idx` (`livreurs_id` ASC) VISIBLE,
  INDEX `fk_commandes_restaurants1_idx` (`restaurants_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_commandes_adresses1`
    FOREIGN KEY (`adresses_clients_id`)
    REFERENCES `mydb`.`adresses_clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_livreurs1`
    FOREIGN KEY (`livreurs_id`)
    REFERENCES `mydb`.`livreurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_restaurants1`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `mydb`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`paiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paiments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commandes_id` INT NOT NULL,
  `numero_transaction` INT NULL,
  `type` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  `montant` VARCHAR(45) NULL,
  `date` DATE NULL,
  INDEX `fk_paiments_commandes1_idx` (`commandes_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_paiments_commandes1`
    FOREIGN KEY (`commandes_id`)
    REFERENCES `mydb`.`commandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`stock_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_produits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employés_id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `descriptif` VARCHAR(45) NULL,
  `quantité` INT NULL,
  `prix` DECIMAL NULL,
  `restaurants_id` INT NOT NULL,
  INDEX `fk_stock_produits_employés1_idx` (`employés_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_stock_produits_restaurants1_idx` (`restaurants_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_produits_employés1`
    FOREIGN KEY (`employés_id`)
    REFERENCES `mydb`.`employés` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_produits_restaurants1`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `mydb`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `descriptif` VARCHAR(45) NULL,
  `prix` DECIMAL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`composition_commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`composition_commandes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commandes_id` INT NOT NULL,
  `stock_produits_id` INT NULL,
  `pizza_id` INT NULL,
  `quantité` INT NULL,
  `prix` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_composition_commandes_commandes1_idx` (`commandes_id` ASC) VISIBLE,
  INDEX `fk_composition_commandes_stock_produits1_idx` (`stock_produits_id` ASC) VISIBLE,
  INDEX `fk_composition_commandes_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_composition_commandes_commandes1`
    FOREIGN KEY (`commandes_id`)
    REFERENCES `mydb`.`commandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_commandes_stock_produits1`
    FOREIGN KEY (`stock_produits_id`)
    REFERENCES `mydb`.`stock_produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_commandes_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`composition_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`composition_pizza` (
  `stock_produits_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `quantité` INT NOT NULL,
  PRIMARY KEY (`stock_produits_id`, `pizza_id`),
  INDEX `fk_stock_produits_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_stock_produits_has_pizza_stock_produits1_idx` (`stock_produits_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_produits_has_pizza_stock_produits1`
    FOREIGN KEY (`stock_produits_id`)
    REFERENCES `mydb`.`stock_produits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_produits_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
